### ISSUE TITLE
License Rstudio

### ISSUE THREAD

**Issue by michellecampo** [broadinstitute/infra20#26]

**Comment by jaredbancroft** [comment]
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**


License info below - We need to make sure that when the container is created and the license applied that any container rebuild will first trigger the license to be deactivated first. If not the license can't be activated again. The better solution is probably to standup a floating license server so that the license isn't tied to the container

https://docs.rstudio.com/connect/1.5.4/admin/licensing-activation.html#floating-licensing

other discussions on licensing for ephemeral containers https://community.rstudio.com/t/rstudio-server-pro-connect-on-kubernetes/57906/2


[karsten@dmz-shiny-proteomics ~]$ sudo /opt/rstudio-connect/bin/license-manager status
RStudio License Manager 1.4.401-6

-- Local license status --

Status: Activated
Product-Key: M6EK-5XPJ-45P8-PXEG-QVGD-YX73-TWTA
Has-Key: Yes
Has-Trial: Yes
Users: 100
User-Activity-Days: 365
Shiny-Users: 100
Allow-APIs: 1
Expiration: 2021-03-01 00:00:00
Days-Left: 49
License-Engine: 4.3.1.0
License-Scope: System

-- Floating license status --

License server not in use.

**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**
**RSTUDIO NEEDS TO BE UNLICENSED BEFORE DESTROYING A CONTAINER**

**Comment by jaredbancroft** [comment]
Helm pre-delete hooks seem promising

https://helm.sh/docs/topics/charts_hooks/

**Comment by jaredbancroft** [comment]
- [ ] you can use tasklists inside issues @zschulte

**Comment by michellecampo** [comment]
Rstudio connect cannot reach the rstudio license server.  

Wrong port?
